CREATE VIEW PUBLIC.RANKING_LOCALIZACAO AS SELECT UUID() as ID, V.TIPO_VOTO, AVG(V.NOTA) AS MEDIA,  V.RESTAURANTE_ID FROM VOTO V JOIN RANKING_VOTOS RV ON RV.VOTOS = V.ID JOIN RANKING R ON R.ID = RV.RANKING 
WHERE V.TIPO_VOTO = 'LOCALIZACAO'
GROUP BY  V.TIPO_VOTO,V.RESTAURANTE_ID;

CREATE VIEW PUBLIC.RANKING_PRECO AS SELECT UUID() as ID, V.TIPO_VOTO, AVG(V.NOTA) AS MEDIA,  V.RESTAURANTE_ID FROM VOTO V JOIN RANKING_VOTOS RV ON RV.VOTOS = V.ID JOIN RANKING R ON R.ID = RV.RANKING 
WHERE V.TIPO_VOTO = 'PRECO'
GROUP BY  V.TIPO_VOTO,V.RESTAURANTE_ID;

CREATE VIEW PUBLIC.RANKING_ATENDIMENTO AS SELECT UUID() as ID, V.TIPO_VOTO, AVG(V.NOTA) AS MEDIA,  V.RESTAURANTE_ID FROM VOTO V JOIN RANKING_VOTOS RV ON RV.VOTOS = V.ID JOIN RANKING R ON R.ID = RV.RANKING 
WHERE V.TIPO_VOTO = 'ATENDIMENTO'
GROUP BY  V.TIPO_VOTO,V.RESTAURANTE_ID;

CREATE VIEW PUBLIC.RANKING_SABOR AS SELECT UUID() as ID, V.TIPO_VOTO, AVG(V.NOTA) AS MEDIA,  V.RESTAURANTE_ID FROM VOTO V JOIN RANKING_VOTOS RV ON RV.VOTOS = V.ID JOIN RANKING R ON R.ID = RV.RANKING 
WHERE V.TIPO_VOTO = 'SABOR'
GROUP BY  V.TIPO_VOTO,V.RESTAURANTE_ID;

CREATE VIEW PUBLIC.RANKING_DEMORA AS SELECT UUID() as ID, V.TIPO_VOTO, AVG(V.NOTA) AS MEDIA,  V.RESTAURANTE_ID FROM VOTO V JOIN RANKING_VOTOS RV ON RV.VOTOS = V.ID JOIN RANKING R ON R.ID = RV.RANKING 
WHERE V.TIPO_VOTO = 'DEMORA'
GROUP BY  V.TIPO_VOTO,V.RESTAURANTE_ID;

CREATE VIEW PUBLIC.RANKING_CUSTO_BENEFICIO AS SELECT UUID() as ID, AVG(V.NOTA) AS MEDIA,  V.RESTAURANTE_ID FROM VOTO V JOIN RANKING_VOTOS RV ON RV.VOTOS = V.ID JOIN RANKING R ON R.ID = RV.RANKING 
GROUP BY  V.RESTAURANTE_ID;

CREATE VIEW PUBLIC.RANKING_CUSTO_BENEFICIO_USUARIO AS SELECT UUID() as ID, AVG(V.NOTA) AS MEDIA,  V.RESTAURANTE_ID, R.USUARIO_ID FROM VOTO V JOIN RANKING_VOTOS RV ON RV.VOTOS = V.ID JOIN RANKING R ON R.ID = RV.RANKING 
GROUP BY V.RESTAURANTE_ID, R.USUARIO_ID;

CREATE VIEW PUBLIC.RANKING_USUARIO AS SELECT UUID() as ID, V.TIPO_VOTO, AVG(V.NOTA) AS MEDIA,  V.RESTAURANTE_ID, R.USUARIO_ID FROM VOTO V JOIN RANKING_VOTOS RV ON RV.VOTOS = V.ID JOIN RANKING R ON R.ID = RV.RANKING 
GROUP BY  V.TIPO_VOTO,V.RESTAURANTE_ID,R.USUARIO_ID;